name: Checking for ISO 3166-2 Updates

on:
  schedule:
    # Run on first of month, every 6 months (https://crontab.guru)
    - cron: '0 0 1 */6 *'

  # allow for workflow to be manually initiated from the Actions tab
  workflow_dispatch:

jobs:
  check_updates:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3 #checkout repo 
      
      #setup python env 
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      
      #export gcloud related Python environment variable
      - name: Export CLOUDSDK_PYTHON
        run: export CLOUDSDK_PYTHON="/usr/bin/python3"

      #setup and authenticate GCP SDK
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
            service_account_email: ${{ secrets.GCP_SA_EMAIL }} 
            service_account_key: ${{ secrets.GCP_SA_KEY }} 
            project_id: ${{ secrets.GCP_PROJECT }}
            export_default_credentials: true
        
      #create, call and delete Cloud Function using gcloud cli
      - name: Create, call and delete check-for-updates Cloud Function
        run: |
          gcloud functions deploy ${{ secrets.GCP_FUNCTION_NAME }} --gen2 --runtime=python3.10 \
              --region=${{ secrets.GCP_REGION }} --source=../iso3166-2-check-for-updates \
              --entry-point=check_for_updates_main --trigger-http --memory=2048MB --timeout=3600 \
              --service-account=${{ secrets.GCP_SA_EMAIL }} \
              --set-env-vars=GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }},GITHUB_API_TOKEN=\
              ${{ secrets.REPO_API_TOKEN }},GITHUB_OWNER=${{ secrets.REPO_OWNER }},GITHUB_REPOS=test_readme,
              BUCKET_NAME=${{ secrets.GCP_BUCKET_NAME }},BLOB_NAME=${{ secrets.GCP_BLOB_NAME }},\
              ARCHIVE_FOLDER=${{ secrets.ARCHIVE_FOLDER }}
          gcloud functions call ${{ secrets.GCP_FUNCTION_NAME }}  --region ${{ secrets.GCP_REGION }} 
          gcloud functions delete ${{ secrets.GCP_FUNCTION_NAME }} --region ${{ secrets.GCP_REGION }} --gen2